// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azpcadkqoljoggbwukxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6cGNhZGtxb2xqb2dnYnd1a3h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MzEzNzgsImV4cCI6MjA2ODMwNzM3OH0.krgeohG9JedBklE-drGp4ngxDLb2WyoMvKu-PKTU73E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});